# ./config/auth0.yml
development:
  auth0_domain: dev-b7w48qu0z5scas2y.us.auth0.com
  auth0_client_id: cCd9heKsPkVHTH44KUFi89lADaEbbbDL
  auth0_client_secret: vt5Aadi-r7lpg_-56ruiLBiHtur-IgEmPC5ONGHgBDpvom5Wrz6ntMogr7A5us8O
